### ISSUE TITLE
json fix and correction for magazine

### ISSUE THREAD

**Issue by TheGoatGod** [Jninja1/Locked-and-Loaded#1]
one of your json files had an extra [] on two lines i have fixed it in the files below and SVD magazine had the wrong ammo type well missing a letter

    VSS.json fix
    ["939", ["VSS_mag"]],
    ["939", ["bigVSS_mag"]]
[VSS.zip](https://github.com/Jninja1/Locked-and-Loaded/files/4345209/VSS.zip)

   SVD.json fix
   "magazines": [["762R", ["SVD_mag"]]]
[SVD.zip](https://github.com/Jninja1/Locked-and-Loaded/files/4345215/SVD.zip)

**Comment by Jninja1** [comment]
Ok, thanks for fixing that for me. I haven’t been able to check the code for a little bit. I appreciate the help  



Sent from myMail for iOS


Tuesday, March 17, 2020, 1:50 PM -0500 from notifications@github.com  <notifications@github.com>:
